# Generated by Django 4.1.3 on 2022-11-17 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=127, validators=[django.core.validators.MaxLengthValidator(127, 'To many charecters')]),
        ),
    ]
