# Generated by Django 4.1.3 on 2022-11-27 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0007_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
