# Generated by Django 4.1.3 on 2022-11-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0008_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default', unique=True),
        ),
    ]
