# Generated by Django 4.1.3 on 2022-11-27 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0009_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='default_user_slug', unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='default_post_slug', unique=True),
        ),
    ]
