# Generated by Django 4.1.3 on 2022-11-28 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0011_alter_customuser_slug_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscriptions',
            field=models.ManyToManyField(null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
