# Generated by Django 4.1.3 on 2022-11-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0014_remove_customuser_subscriptions_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_text',
            field=models.CharField(default='abc', editable=False, max_length=127),
        ),
    ]
