# Generated by Django 4.1.3 on 2022-11-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0015_post_test_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='test_text',
            field=models.CharField(default='abc', max_length=127),
        ),
    ]
