# Generated by Django 4.1.3 on 2022-11-30 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0017_post_int_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='int_field',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(5, 'to many smth'), django.core.validators.MinValueValidator(0, 'to small')]),
        ),
    ]
