# Generated by Django 4.1.3 on 2022-11-30 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0018_alter_post_int_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='int_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='test_text',
        ),
    ]
