# Generated by Django 4.1.3 on 2022-11-30 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0020_post_max_passed_post_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='passed',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
