# Generated by Django 4.1.3 on 2022-11-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_auth', '0023_alter_post_max_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='max_passed',
        ),
        migrations.RemoveField(
            model_name='post',
            name='passed',
        ),
    ]
